version: '3.7'
services:
  mysql1:
    image: sergiotabanelli/mysqlreader
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: ["--server-id=1","--loose-group-replication-local-address=mysql1:33061","--loose-group-replication-group-seeds=mysql1:33061,mysql2:33061,mysql3:33061","--loose-group-replication-start-on-boot=ON","--loose-group-replication-bootstrap-group=ON"]
    volumes:
      - type: bind
        source: ./docker/mysql/initdb.gr.d
        target: /docker-entrypoint-initdb.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/bootstrap.gr.d
        target: /docker-entrypoint-bootstrap.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/conf.gr.d
        target: /etc/mysql/conf.d
        consistency: delegated
  mysql2:
    image: sergiotabanelli/mysqlreader
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: ["--server-id=2","--loose-group-replication-local-address=mysql2:33061","--loose-group-replication-group-seeds=mysql1:33061,mysql2:33061,mysql3:33061","--loose-group-replication-start-on-boot=ON"]
    volumes:
      - type: bind
        source: ./docker/mysql/initdb.gr.d
        target: /docker-entrypoint-initdb.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/start.gr.d
        target: /docker-entrypoint-bootstrap.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/conf.gr.d
        target: /etc/mysql/conf.d
        consistency: delegated
  mysql3:
    image: sergiotabanelli/mysqlreader
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: ["--server-id=3","--loose-group-replication-local-address=mysql3:33061","--loose-group-replication-group-seeds=mysql1:33061,mysql2:33061,mysql3:33061","--loose-group-replication-start-on-boot=ON"]
    volumes:
      - type: bind
        source: ./docker/mysql/initdb.gr.d
        target: /docker-entrypoint-initdb.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/start.gr.d
        target: /docker-entrypoint-bootstrap.d
        consistency: delegated
      - type: bind
        source: ./docker/mysql/conf.gr.d
        target: /etc/mysql/conf.d
        consistency: delegated
  memcached:
    image: memcached
  proxysqlc19-1:
    image: sergiotabanelli/proxysqlc19
    ports:
      - "16032:6032"
      - "16033:6033"
  proxysqlc19-2:
    image: sergiotabanelli/proxysqlc19
    ports:
      - "26032:6032"
      - "26033:6033"
